name: CI
on:
  push:
    branches:
      - main
jobs:
  swift-format:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run SwiftFormat with License Header
      run: |
        # Read LICENSE file, add `// ` before each line.
        LICENSE_BLOCK=$(sed 's/^/\/\/ /' LICENSE)
        swiftformat Sources --header "$(LICENSE_BLOCK)"
    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if ! git diff --quiet --staged; then
          git commit -m "Apply SwiftFormat with License Header"
          git push origin main
        else
          echo "No changes to commit"
        fi
