# Simple workflow for deploying static content to GitHub Pages
name: Deploy Documentation to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Pages
        uses: actions/configure-pages@main
      - name: Build DocC
        run: |
          xcodebuild docbuild -scheme AppLogger \
            -derivedDataPath /tmp/docbuild \
            -destination 'generic/platform=iOS';
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting /tmp/docbuild/Build/Products/Debug-iphoneos/AppLogger.doccarchive \
            --hosting-base-path swiftui-property-picker \
            --output-path docs;
          echo "<script>window.location.href += \"/documentation/applogger\"</script>" > docs/index.html;
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload docs folder
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
